def solution():
    return len(set([a ** b for a in range(2, 101) for b in range(2, 101)]))


if __name__ == "__main__":
    print(
        "The number of distinct terms generated by the sequence "
        "a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100 is equal {}".format(solution())
    )
